### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by MorrisJobke** [beaucollins/psalm-annotations-action#30]
I wanted to try the action and run into following problem with the example configuration from the Readme.

```
Run beaucollins/psalm-annotations-action@master
  with:
    report_path: ./report.json
    report_name: psalm
    report_title: Psalm PHP Static Analysis
    report_type: psalm
/home/runner/work/_actions/beaucollins/psalm-annotations-action/master/dist/index.js:85
    end_line: message.endLine ?? message.line,
                               ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

Looks like some runtime has changed and therefore the syntax is not compatible anymore, or do I get it wrong?

**Comment by beaucollins** [comment]
Yes, looks like the machine that built the latest code was using a newer node version than node12 so it failed to transform the nullish coalescing operator which was introduce in node14.

I fixed it up and you can use `beaucollins/psalm-annotations-action@v1.4.0` 

Also, the `GITHUB_TOKEN` needs to be passed via the `env:` section of the YML. I updated the README and the examples in this repo show the correct usage now.

An example of the annotations this action produces is at the bottom of this PR:

https://github.com/beaucollins/psalm-annotations-action/pull/31/files

**Comment by beaucollins** [comment]
Builds show it working again, marking as fixed. Re-open if you are still having issues.

**Comment by MorrisJobke** [comment]
@beaucollins Thanks - worked so far 👍
